// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1_B6yYsrTY0UU9j5t53VeVmAPT7bxMnA',
    appId: '1:279656815637:web:b6d1a72b1885ad8b92c21c',
    messagingSenderId: '279656815637',
    projectId: 'canarias-luxury',
    authDomain: 'canarias-luxury.firebaseapp.com',
    storageBucket: 'canarias-luxury.appspot.com',
    measurementId: 'G-P6C30BPMRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-AuJ2_O0r15Gjky7RAH-D3wcfmsp14U',
    appId: '1:279656815637:android:6cdfa07e89e5d3d292c21c',
    messagingSenderId: '279656815637',
    projectId: 'canarias-luxury',
    storageBucket: 'canarias-luxury.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBooZFMfmJKiGHDzA2qghoIlOVVeNJfxho',
    appId: '1:279656815637:ios:03d539aa4906f73692c21c',
    messagingSenderId: '279656815637',
    projectId: 'canarias-luxury',
    storageBucket: 'canarias-luxury.appspot.com',
    iosClientId: '279656815637-eekfummbsqu68en9t8v2rcoeg22gotdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoDam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBooZFMfmJKiGHDzA2qghoIlOVVeNJfxho',
    appId: '1:279656815637:ios:03d539aa4906f73692c21c',
    messagingSenderId: '279656815637',
    projectId: 'canarias-luxury',
    storageBucket: 'canarias-luxury.appspot.com',
    iosClientId: '279656815637-eekfummbsqu68en9t8v2rcoeg22gotdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoDam',
  );
}
